export { default as Home } from "./Home"
export { default as About } from "./About"
export { default as Service } from "./Service"
export { default as Blog } from "./Blog"
export { default as Contact } from "./Contact"
export { default as Error } from "./Error"
export { default as BlogDetails } from "./blog/BlogDetails"
export { default as BlogGrid } from "./blog/BlogGrid"